/*
---------------------------------------------------------------------
Magnitude Analysis
---------------------------------------------------------------------

Script Purpose:
	Understand data dstributions across categories. Group measures
	by dimensions

Methods:
	Use SUM, AVG or COUNT to aggregate measure and group by
	a dimension

---------------------------------------------------------------------
*/

-- Find the total customers by the country
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC
;

-- Find the total customes by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_key) DESC
;

-- Find total products by category
SELECT
	category,
	COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_id) DESC
;

-- Find the average cost in each category
SELECT
	category,
	AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC
;

-- Find the total revenue generated by each category
SELECT
	p.category,
	SUM(s.sales) AS total_revenue
FROM
	gold.fact_sales s
LEFT JOIN
	gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY SUM(s.sales) DESC
;

-- Find the total revenue generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales) AS total_revenue
FROM
	gold.fact_sales s
LEFT JOIN
	gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY SUM(s.sales) DESC
;

-- What is the distribution of sold items across countries
SELECT
	c.country,
	SUM(s.quantity) AS total_items_sold
FROM
	gold.fact_sales s
LEFT JOIN
	gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY SUM(s.quantity) DESC
;
